server:
  port: 9090

# Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka/'

# Credential
spring:
  security:
    user:
      name: 'admin'
      password: 'admin'